### PR TITLE
Fix for typo in f18/test-lit/CMakeLists.txt 

### PR DESCRIPTION
**Pull request by Sameeranjoshi**
I think the flag(FLANG_TEST_DEPENDS) may be getting neglected and not checking for dependencies.

### CODE REVIEW

**Comment by Sameeranjoshi** [comment]
Is this due to <path to llvm_install_location>/bin doesn't have llvm-lit, is the -DLLVM_INSTALL_UTILS=ON set in while building llvm?

**Comment by tskeith** [comment]
With this change I get the following error from cmake:
```
CMake Error at /Users/tsk/llvm/f18-llvm/build/Release-clang-9/lib/cmake/llvm/AddLLVM.cmake:1546 (add_dependencies):
  The dependency target "flang" of target "check-all" does not exist.
Call Stack (most recent call first):
  /Users/tsk/llvm/f18-llvm/build/Release-clang-9/lib/cmake/llvm/AddLLVM.cmake:1567 (add_lit_target)
  test-lit/CMakeLists.txt:22 (add_lit_testsuite)
```
And a similar one for `llvm-lit`.

Does this require a change to the build instructions?

**Comment by CarolineConcatto** [comment]
Very odd, I also have the message, but make check-all works just fine:

**Comment by CarolineConcatto** [comment]
I haven't noticed this problem before, but I have it also. 
The reason I did not see it was becasue make check-all works.

**Comment by Sameeranjoshi** [comment]
Thanks @CarolineConcatto @DavidTruby 
Closing issue as https://github.com/flang-compiler/f18/pull/1033 addresses the issue.

**Pull request closed without merging**
