### PR TITLE
Update C++style.md

### PR DESCRIPTION
**Pull request by klausler**
Now that we have a bunch of code in the source base, adjust guidelines to recommend compatibility with established precedents.

### CODE REVIEW

**Comment by sscalpone** [comment]
If the code in question is derived from llvm code, and looks more like llvm code, then it makes sense to follow the llvm naming style more directly in that code. (I don't know how this rule would be applied in the code in question; I'm just proposing it as a general rule.)

**Comment by tskeith** [comment]
> If the code in question is derived from llvm code, and looks more like llvm code, then it makes sense to follow the llvm naming style more directly in that code. (I don't know how this rule would be applied in the code in question; I'm just proposing it as a general rule.)

I would say no. I think consistency within f18 should take precedence over consistency with llvm.

**Comment by schweitzpgi** [comment]
> If the code in question is derived from llvm code, and looks more like llvm code, then it makes sense to follow the llvm naming style more directly in that code. (I don't know how this rule would be applied in the code in question; I'm just proposing it as a general rule.)

The FIR code leverages LLVM code.

**Comment by klausler** [comment]
> The FIR code leverages LLVM code.

This is known.  The questions of precedents to follow are not immediately clarified, however, and may well not be the same in all situations.

For example, f18 code is pretty googley when it comes to accessors and mutators of private data members.  I don't think that new classes with accessors and mutators should be different from existing accessors and mutators elsewhere in f18 unless the new class inherits from an llvm class with a clear means of naming its accessors and mutators.

On the other hand, llvmish names like `dump()` might seem gratuitously weird to LLVM programmers if we changed them.

**Comment by sscalpone** [comment]
I think the restriction of "inherits from llvm class" is too strict.  I think new code should be written in the style of the subsystem of which it is part.  So if the new code mostly interacts with llvm-ish code and is mostly in the style of llvm, then it should follow the naming conventions of llvm more directly.

**Comment by tskeith** [comment]
> I think the restriction of "inherits from llvm class" is too strict. I think new code should be written in the style of the subsystem of which it is part. So if the new code mostly interacts with llvm-ish code and is mostly in the style of llvm, then it should follow the naming conventions of llvm more directly.

I think this is too vague to follow. What does "mostly interacts with" mean? If you have code written in the standard style and then add interactions with llvm, do you change the names to follow the llvm conventions? Over what scope -- function, file, namespace?

If you want to use two sets of naming conventions, there has to be easy-to-follow rules about which apply where.

**Comment by schweitzpgi** [comment]
`namespace` boundaries seem reasonable.  It is highly desirable (even mandatory in some sense) to leverage other well-tested libraries and do so in a way that doesn't require ubiquitous and gratuitous case-and-underscore identifier replacement.  For example, the STL doesn't conform to the F18 style convention, and I haven't seen anyone seriously suggest it must undergo a comprehensive identifier replacement to make it conform.  Other libraries and the code that is building on them should be given the same consideration.

**Comment by klausler** [comment]
> `namespace` boundaries seem reasonable. It is highly desirable (even mandatory in some sense) to leverage other well-tested libraries and do so in a way that doesn't require ubiquitous and gratuitous case-and-underscore identifier replacement. For example, the STL doesn't conform to the F18 style convention, and I haven't seen anyone seriously suggest it must undergo a comprehensive identifier replacement to make it conform. Other libraries and the code that is building on them should be given the same consideration.

What do you mean by "ubiquitous and gratuitous case-and-underscore identifier replacement"?

**Comment by schweitzpgi** [comment]
> What do you mean by "ubiquitous and gratuitous case-and-underscore identifier replacement"?

I was parroting your line about the `dump()` example.  Who wants to remember that one set of classes uses `Dump()` while everywhere else in LLVM/clang/etc.-land, you use `dump()`? For another example, the same could apply to using STL iterators. Who would argue that it was an improvement to build custom container classes that use `Iterator`, `ConstIterator`, `Begin`, and `End` to blindly follow the style guide and thus immediately rule out using all the STL algorithms?

**Comment by tskeith** [comment]
> > What do you mean by "ubiquitous and gratuitous case-and-underscore identifier replacement"?
> 
> I was parroting your line about the `dump()` example. Who wants to remember that one set of classes uses `Dump()` while everywhere else in LLVM/clang/etc.-land, you use `dump()`?

Using `Dump()` in f18 code and `dump()` in LLVM code seems perfectly reasonable to me. Using `Dump()` in parts of f18 and `dump()` in other parts less so.

> For another example, the same could apply to using STL iterators. Who would argue that it was an improvement to build custom container classes that use `Iterator`, `ConstIterator`, `Begin`, and `End` to blindly follow the style guide and thus immediately rule out using all the STL algorithms?

This is nonsense. Calling APIs is completely different from writing our own code.

**Pull request closed without merging**
