### PR TITLE
Rename features.h

### PR DESCRIPTION
**Pull request by sscalpone**
Rename features.h because many linux systems have an include file called features.h which can complicate makefiles that use a search path.

### CODE REVIEW

**Comment by klausler** [comment]
The guard macro in the header file needs to be updated if its name is changed.

The features described in the header are not really flang features; Fortran-features.h would be a better name.

Is this a real problem?  If so, should be rename all our header files?

**Comment by sscalpone** [comment]
> The guard macro in the header file needs to be updated if its name is changed.
> 
> The features described in the header are not really flang features; Fortran-features.h would be a better name.
> 
> Is this a real problem? If so, should be rename all our header files?

There are other conflicts, in lib/evaluate, e.g. complex.h.  I'm willing to wait for a complaint.

**Comment by tskeith** [comment]
I don't understand. When is this a problem?

**Comment by sscalpone** [comment]
> I don't understand. When is this a problem?

When building f18 in the llvm tree, compiling parse-tree.cc, there's eventually an include of the system include file "functional" from idioms.h, which eventually includes /usr/include/.../os_defines.h which includes features.h.  Instead of /usr/include/features.h, the compiler chooses the f18 features.h instead.  This is with gcc 8.3 on a regular linux system.

**Pull request merged**
