### PR TITLE
Added a test case for #794-Check for PURE procedures containing image…

### PR DESCRIPTION
**Pull request by kiranktp**
Added a test case to validate presence of image control statements in PURE procedures.

### CODE REVIEW

**Comment by tskeith** [comment]
The tests look good, but I think they should go into `call10.f90`. That's where SYNC ALL is already being tested with a TODO for the other cases.

**Comment by kiranktp** [comment]
I have removed the newly added test file by moving the checks to call10.f90 file.

**Comment by sscalpone** [comment]
@kiranktp Please squash and make a single commit.

**Comment by kiranktp** [comment]
> @kiranktp Please squash and make a single commit.

I have squashed multiple commit and made it a single commit.

**Pull request merged**
