### PR TITLE
Revert "Remove needless braces"

### PR DESCRIPTION
**Pull request by peterwaller-arm**
This reverts commit edd18355be574122aaa9abf58c15d8c50fb085a1.

This fixes the build for me on Ubuntu 18.04 under gcc 7.4.0.

Please see #527 for detailed discussion.

### CODE REVIEW

**Comment by klausler** [comment]
Can you clarify whether the braces are required by C++, or are they required to work around a bug in a particular version of GCC?

**Comment by peterwaller-arm** [comment]
@klausler, apologies, at this stage I did not dig deeper to understand the failure, just applied a revert since it was a rapid and reasonably uncontroversial thing to do.

As you asked, I have further localized the issue to the `return {std::move(...)}` cases. The other cases do compile at least.

**Comment by klausler** [comment]
> @klausler, apologies, at this stage I did not dig deeper to understand the failure, just applied a revert since it was a rapid and reasonably uncontroversial thing to do.
> 
> As you asked, I have further localized the issue to the `return {std::move(...)}` cases. The other cases do compile at least.

Excellent.  That narrows down the area of potential problems to avoid in those older GCC versions.  Thanks for digging further.

**Comment by peterwaller-arm** [comment]
You're welcome :)

**Pull request merged**
