### PR TITLE
Update CMakeList.txt to allow linking with LLVM libc++

### PR DESCRIPTION
**Pull request by sscalpone**
To use LLVM's libc++ instead of GCC's libstdc++, define
BUILD_WITH_CLANG_LIBRARIES on the cmake command line to
be the path to a clang installation with bin, lib, etc.
For this to work, BUILD_WITH_CLANG must be defined too.

### CODE REVIEW

**Comment by sscalpone** [comment]
Pete, you need to pass in LLVM_DIR too.

**Comment by psteinfeld** [comment]
I'm not sure how to define LLVM_DIR correctly.  Here's my latest cmake command, which also fails when I do a "make" --
cmake -D CMAKE_BUILD_TYPE=Release -D CMAKE_PREFIX_PATH=/home/sw/thirdparty/llvm/linux86-64/latest -D BUILD_WITH_CLANG_LIBRARIES=/home/sw/thirdparty/llvm/linux86-64/latest -D BUILD_WITH_CLANG=/home/sw/thirdparty/llvm/linux86-64/latest/ -D LLVM_DIR=/home/sw/thirdparty/llvm/linux86-64/latest/lib/cmake/llvm ..

What's a command that will succeed?

**Comment by klausler** [comment]
> I'm not sure how to define LLVM_DIR correctly. Here's my latest cmake command, which also fails when I do a "make" --
> cmake -D CMAKE_BUILD_TYPE=Release -D CMAKE_PREFIX_PATH=/home/sw/thirdparty/llvm/linux86-64/latest -D BUILD_WITH_CLANG_LIBRARIES=/home/sw/thirdparty/llvm/linux86-64/latest -D BUILD_WITH_CLANG=/home/sw/thirdparty/llvm/linux86-64/latest/ -D LLVM_DIR=/home/sw/thirdparty/llvm/linux86-64/latest/lib/cmake/llvm ..
> 
> What's a command that will succeed?

Try setting `LLVM_DIR` in the environment instead.

**Comment by schweitzpgi** [comment]
libc++ is not built as part of our release tools.

**Comment by psteinfeld** [comment]
Thanks.

I changed my environment, and now ehen I look at my environment, I see

LLVM_DIR=/home/sw/thirdparty/llvm/linux86-64/latest/

Things still don't work.

**Comment by sscalpone** [comment]
There's nothing on /home/sw/thirdparty that will satisfy BUILD_WITH_CLANG_LIBRARIES.  One build-lin64, you can try /local/home/qa/llvm/install2.

**Comment by psteinfeld** [comment]
OK.  I logged onto build-lin64 and tried to build with this command line -- 

cmake -D CMAKE_BUILD_TYPE=Release -D CMAKE_PREFIX_PATH=/home/sw/thirdparty/llvm/linux86-64/latest -D BUILD_WITH_CLANG_LIBRARIES=/local/home/qa/llvm/install2 -D BUILD_WITH_CLANG=/local/home/qa/llvm/install2 -D LLVM_DIR=/local/home/qa/llvm/install2 ..

All of the compilations succeeded, but I got many more warnings that a normal build.

After the compilations, though, the linking of f18 failed.  Here's the relevant excerpt from the log file:

[100%] Linking CXX executable f18
clang-7: warning: argument unused during compilation: '-nostdinc++' [-Wunused-command-line-argument]
/home/sw/thirdparty/llvm/linux86-64/latest/lib/libLLVMSupport.a(Error.cpp.o): In function `(anonymous namespace)::ErrorErrorCategory::~ErrorErrorCategory()':
Error.cpp:(.text._ZN12_GLOBAL__N_118ErrorErrorCategoryD2Ev+0xb): undefined reference to `std::_V2::error_category::~error_category()'
/home/sw/thirdparty/llvm/linux86-64/latest/lib/libLLVMSupport.a(Error.cpp.o): In function `(anonymous namespace)::ErrorErrorCategory::~ErrorErrorCategory()':
Error.cpp:(.text._ZN12_GLOBAL__N_118ErrorErrorCategoryD0Ev+0xf): undefined reference to `std::_V2::error_category::~error_category()'
/home/sw/thirdparty/llvm/linux86-64/latest/lib/libLLVMSupport.a(Error.cpp.o): In function `llvm::object_deleter<(anonymous namespace)::ErrorErrorCategory>::call(void*)':
Error.cpp:(.text._ZN4llvm14object_deleterIN12_GLOBAL__N_118ErrorErrorCategoryEE4callEPv+0x14): undefined reference to `std::_V2::error_category::~error_category()'
/home/sw/thirdparty/llvm/linux86-64/latest/lib/libLLVMSupport.a(Error.cpp.o): In function `llvm::ErrorInfoBase::message[abi:cxx11]() const':
Error.cpp:(.text._ZNK4llvm13ErrorInfoBase7messageB5cxx11Ev[_ZNK4llvm13ErrorInfoBase7messageB5cxx11Ev]+0xb0): undefined reference to `std::__throw_logic_error(char const*)'

**Comment by sscalpone** [comment]
It's not immediately obvious how CMake wants me to fix  '-nostdinc++' .  The issue is that clang needs this option when compiling but complains about this option when linking but CMake only provides a single CMAKE_CXX_FLAGS variable that is used for compiling and linking.

**Comment by sscalpone** [comment]
I passed the compilation warning over to Eric.

**Comment by tskeith** [comment]
You could add `-Wno-unused-command-line-argument` to `CMAKE_EXE_LINKER_FLAGS`.
Of course, it would suppress all unused argument warnings on the link command.

**Comment by sscalpone** [comment]
I'd rather not miss a warning because we decided to suppress warning.  I'd prefer that my eyes let me down & I missed a warning because it was mixed in with other warning.

**Pull request merged**
